version: '3'

services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./gateway:/usr/src/app
    networks:
      - app-network
    links:
      - users

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./users:/usr/src/app
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge